version: '2.4'

services:
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_PASSWORD=YOUR_PASS
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:4.25
    ports:
      - '5050:5050'
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=YOUR_PASS
      - PGADMIN_LISTEN_PORT=5050
    depends_on:
      - db

volumes:
    db-data:
